version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_UCSP_DB}
      POSTGRES_USER: ${POSTGRES_UCSP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_UCSP_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      POSTGRES_USER: ${POSTGRES_UCSP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_UCSP_PASSWORD}
      POSTGRES_DB: ${POSTGRES_UCSP_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    command: ["npm", "run", "dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
